cmake_minimum_required(VERSION 3.16)

# Include centralized dependency configuration
include(${CMAKE_CURRENT_SOURCE_DIR}/cmake/dependencies.cmake)

if(BUILD_TESTS)
  # CMocka
  dep_cmocka()
  set(CMocka_DEVEL_PKG   cmocka-${DEP_CMOCKA_VERSION}.tar.xz)
  set(CMocka_PATH        ${CMAKE_CURRENT_SOURCE_DIR}/deps_${PLATFORM}/cmocka-${DEP_CMOCKA_VERSION})
  set(CMocka_BUILD_PATH  ${CMAKE_CURRENT_SOURCE_DIR}/deps_${PLATFORM}/cmocka-${DEP_CMOCKA_VERSION}_build)
  set(CMocka_INCLUDE_DIR ${CMocka_PATH}/include)
  set(CMocka_LIBRARY     ${CMocka_BUILD_PATH}/src/cmocka.lib)

  ExternalProject_Add(CMocka_devel
    URL ${DEP_CMOCKA_URL_BASE}/${CMocka_DEVEL_PKG}
    URL_HASH SHA1=${DEP_CMOCKA_SHA1}
    DOWNLOAD_DIR ${CMAKE_CURRENT_SOURCE_DIR}/deps_${PLATFORM}
    DOWNLOAD_NO_PROGRESS true
    DOWNLOAD_EXTRACT_TIMESTAMP true
    TLS_VERIFY true
    SOURCE_DIR ${CMocka_PATH}
    BINARY_DIR ${CMocka_BUILD_PATH}
    BUILD_BYPRODUCTS ${CMocka_LIBRARY}

    CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>
      -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
      -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
      -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
      -DCMAKE_MAKE_PROGRAM=${CMAKE_MAKE_PROGRAM}
      -DCMAKE_DISABLE_FIND_PACKAGE_Doxygen=ON
      -DBUILD_SHARED_LIBS=ON
      -DWITH_EXAMPLES=OFF

    PATCH_COMMAND ${CMAKE_COMMAND} -DCMocka_PATH=${CMocka_PATH} -P ${CMAKE_CURRENT_SOURCE_DIR}/cmake/patch_cmocka.cmake

    INSTALL_COMMAND ${CMAKE_COMMAND} -E copy
      ${CMocka_PATH}_build/src/cmocka.dll ${CMAKE_CURRENT_SOURCE_DIR}/export
    )
endif(BUILD_TESTS)

# cJSON
dep_cjson()
set(CJSON_DEVEL_PKG   "v${DEP_CJSON_VERSION}.zip")
set(CJSON_PATH        ${CMAKE_CURRENT_SOURCE_DIR}/deps_${PLATFORM}/CJSON-${DEP_CJSON_VERSION})
set(CJSON_INCLUDE_DIR ${CJSON_PATH})
set(CJSON_LIBRARY     ${CJSON_PATH}_build/cjson.lib)

ExternalProject_Add(cJSON_devel
  URL ${DEP_CJSON_URL_BASE}/${CJSON_DEVEL_PKG}
  URL_HASH SHA1=${DEP_CJSON_SHA1_WINDOWS}
  DOWNLOAD_DIR ${CMAKE_CURRENT_SOURCE_DIR}/deps_${PLATFORM}
  DOWNLOAD_NO_PROGRESS true
  DOWNLOAD_EXTRACT_TIMESTAMP true
  TLS_VERIFY true
  SOURCE_DIR ${CJSON_PATH}/
  BINARY_DIR ${CJSON_PATH}_build/
  BUILD_BYPRODUCTS ${CJSON_LIBRARY}
  CMAKE_ARGS
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
    -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
    -DCMAKE_MAKE_PROGRAM=${CMAKE_MAKE_PROGRAM}
    -DCMAKE_POLICY_VERSION_MINIMUM=3.5
  INSTALL_COMMAND
    ${CMAKE_COMMAND} -E copy ${CJSON_PATH}_build/cjson.dll ${CMAKE_CURRENT_SOURCE_DIR}/export
)

# CANvenient
dep_canvenient()
set(CANVENIENT_DEVEL_PKG "CANvenient-v${DEP_CANVENIENT_VERSION}.zip")
set(CANVENIENT_PATH      ${CMAKE_CURRENT_SOURCE_DIR}/deps_${PLATFORM}/CANvenient-${DEP_CANVENIENT_VERSION})

set(CANVENIENT_PLATFORM "x64")
if(CMAKE_SIZEOF_VOID_P EQUAL 4)
  set(CANVENIENT_PLATFORM "x86")
endif()

ExternalProject_Add(CANvenient_devel
  URL ${DEP_CANVENIENT_URL_BASE_WINDOWS}/${CANVENIENT_DEVEL_PKG}
  URL_HASH SHA1=${DEP_CANVENIENT_SHA1_WINDOWS}
  DOWNLOAD_DIR ${CMAKE_CURRENT_SOURCE_DIR}/deps_${PLATFORM}
  DOWNLOAD_NO_PROGRESS true
  DOWNLOAD_EXTRACT_TIMESTAMP true
  TLS_VERIFY true
  SOURCE_DIR ${CANVENIENT_PATH}/
  BUILD_BYPRODUCTS ${CANVENIENT_PATH}/lib/${CANVENIENT_PLATFORM}/CANvenient.lib

  BUILD_COMMAND ${CMAKE_COMMAND} -E echo "Skipping build step."

  INSTALL_COMMAND ${CMAKE_COMMAND} -E copy
    ${CANVENIENT_PATH}/bin/${CANVENIENT_PLATFORM}/CANusbM.dll
    ${CANVENIENT_PATH}/bin/${CANVENIENT_PLATFORM}/canchd_64.dll
    ${CANVENIENT_PATH}/bin/${CANVENIENT_PLATFORM}/canL2_64.dll
    ${CANVENIENT_PATH}/bin/${CANVENIENT_PLATFORM}/canlib32.dll
    ${CANVENIENT_PATH}/bin/${CANVENIENT_PLATFORM}/CANvenient.dll
    ${CANVENIENT_PATH}/bin/${CANVENIENT_PLATFORM}/PCANBasic.dll
    ${CMAKE_CURRENT_SOURCE_DIR}/export

    PATCH_COMMAND ${CMAKE_COMMAND} -E copy
      "${CMAKE_CURRENT_SOURCE_DIR}/cmake/dep_CANvenient.cmake" ${CANVENIENT_PATH}/CMakeLists.txt
)

set(CANVENIENT_INCLUDE_DIR ${CANVENIENT_PATH}/include)
set(CANVENIENT_LIBRARY     ${CANVENIENT_PATH}/lib/${CANVENIENT_PLATFORM}/CANvenient.lib)

# pocketpy
dep_pocketpy()
set(POCKETPY_DEVEL_PKG   "v${DEP_POCKETPY_VERSION}.zip")
set(POCKETPY_PATH        ${CMAKE_CURRENT_SOURCE_DIR}/deps_${PLATFORM}/pocketpy-${DEP_POCKETPY_VERSION})
set(POCKETPY_INCLUDE_DIR ${POCKETPY_PATH}/include)
set(POCKETPY_LIBRARY     ${POCKETPY_PATH}_build/pocketpy.lib)

ExternalProject_Add(pocketpy_devel
  URL ${DEP_POCKETPY_URL_BASE}/${POCKETPY_DEVEL_PKG}
  URL_HASH SHA1=${DEP_POCKETPY_SHA1_WINDOWS}
  DOWNLOAD_DIR ${CMAKE_CURRENT_SOURCE_DIR}/deps_${PLATFORM}
  DOWNLOAD_NO_PROGRESS true
  DOWNLOAD_EXTRACT_TIMESTAMP true
  TLS_VERIFY true
  SOURCE_DIR ${POCKETPY_PATH}/
  BINARY_DIR ${POCKETPY_PATH}_build/
  BUILD_BYPRODUCTS ${POCKETPY_LIBRARY}
  CMAKE_ARGS
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
    -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
    -DCMAKE_MAKE_PROGRAM=${CMAKE_MAKE_PROGRAM}
    -DPK_ENABLE_OS=ON
    -DPK_BUILD_MODULE_LZ4=OFF
  INSTALL_COMMAND ${CMAKE_COMMAND} -E copy
    ${POCKETPY_PATH}_build/pocketpy.dll ${CMAKE_CURRENT_SOURCE_DIR}/export
  )

# inih
dep_inih()
set(INIH_DEVEL_PKG   r${DEP_INIH_VERSION}.zip)
set(INIH_PATH        ${CMAKE_CURRENT_SOURCE_DIR}/deps_${PLATFORM}/inih-${DEP_INIH_VERSION})
set(INIH_INCLUDE_DIR ${INIH_PATH})
set(INIH_LIBRARY     ${INIH_PATH}_build/inih.lib)

ExternalProject_Add(inih_devel
  URL ${DEP_INIH_URL_BASE}/${INIH_DEVEL_PKG}
  URL_HASH SHA1=${DEP_INIH_SHA1_WINDOWS}
  DOWNLOAD_DIR ${CMAKE_CURRENT_SOURCE_DIR}/deps_${PLATFORM}
  DOWNLOAD_NO_PROGRESS true
  DOWNLOAD_EXTRACT_TIMESTAMP true
  TLS_VERIFY true
  SOURCE_DIR ${INIH_PATH}/
  BINARY_DIR ${INIH_PATH}_build/
  BUILD_BYPRODUCTS ${INIH_LIBRARY}
  CMAKE_ARGS
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
    -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
    -DCMAKE_MAKE_PROGRAM=${CMAKE_MAKE_PROGRAM}

  INSTALL_COMMAND ${CMAKE_COMMAND} -E echo "Skipping install step."

  PATCH_COMMAND ${CMAKE_COMMAND} -E copy
    "${CMAKE_CURRENT_SOURCE_DIR}/cmake/dep_inih.cmake" ${INIH_PATH}/CMakeLists.txt
)

# isocline
dep_isocline()
set(ISOCLINE_DEVEL_PKG   "v${DEP_ISOCLINE_VERSION}.zip")
set(ISOCLINE_PATH        ${CMAKE_CURRENT_SOURCE_DIR}/deps_${PLATFORM}/isocline-${DEP_ISOCLINE_VERSION})
set(ISOCLINE_INCLUDE_DIR ${ISOCLINE_PATH}/include)
set(ISOCLINE_LIBRARY     ${ISOCLINE_PATH}_build/isocline.lib)

ExternalProject_Add(isocline_devel
  URL ${DEP_ISOCLINE_URL_BASE}/${ISOCLINE_DEVEL_PKG}
  URL_HASH SHA1=${DEP_ISOCLINE_SHA1_WINDOWS}
  DOWNLOAD_DIR ${CMAKE_CURRENT_SOURCE_DIR}/deps_${PLATFORM}
  DOWNLOAD_NO_PROGRESS true
  DOWNLOAD_EXTRACT_TIMESTAMP true
  TLS_VERIFY true
  SOURCE_DIR ${ISOCLINE_PATH}/
  BINARY_DIR ${ISOCLINE_PATH}_build/
  BUILD_BYPRODUCTS ${ISOCLINE_LIBRARY}
  CMAKE_ARGS
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCMAKE_SYSTEM_NAME=Windows
    -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
    -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
    -DCMAKE_MAKE_PROGRAM=${CMAKE_MAKE_PROGRAM}
    -DIC_BUILD_TESTS=OFF

  PATCH_COMMAND ${CMAKE_COMMAND} -DIS_WINDOWS=1 -DISOCLINE_PATH=${ISOCLINE_PATH} -P ${CMAKE_CURRENT_SOURCE_DIR}/cmake/patch_isocline.cmake

  INSTALL_COMMAND ${CMAKE_COMMAND} -E echo "Skipping install step."
  )

# Lua
dep_lua()
set(LUA_DEVEL_PKG   lua-${DEP_LUA_VERSION}.tar.gz)
set(LUA_PATH        ${CMAKE_CURRENT_SOURCE_DIR}/deps_${PLATFORM}/lua-${DEP_LUA_VERSION}_${PLATFORM})
set(LUA_INCLUDE_DIR ${LUA_PATH}/src)
set(LUA_LIBRARY     ${LUA_PATH}/lua.lib)

ExternalProject_Add(Lua_devel
  URL ${DEP_LUA_URL_BASE}/${LUA_DEVEL_PKG}
  URL_HASH SHA1=${DEP_LUA_SHA1_WINDOWS}
  DOWNLOAD_DIR ${CMAKE_CURRENT_SOURCE_DIR}/deps_${PLATFORM}
  DOWNLOAD_NO_PROGRESS true
  DOWNLOAD_EXTRACT_TIMESTAMP true
  TLS_VERIFY true
  SOURCE_DIR ${LUA_PATH}/
  BUILD_BYPRODUCTS ${LUA_LIBRARY}
  CMAKE_ARGS
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
    -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
    -DCMAKE_MAKE_PROGRAM=${CMAKE_MAKE_PROGRAM}

  BUILD_IN_SOURCE 1
  INSTALL_COMMAND ${CMAKE_COMMAND} -E echo "Skipping install step."

  PATCH_COMMAND ${CMAKE_COMMAND} -E copy
    "${CMAKE_CURRENT_SOURCE_DIR}/cmake/dep_lua.cmake" ${LUA_PATH}/CMakeLists.txt
)

# SDL3
dep_sdl3()

set(SDL3_DEVEL_PKG SDL3-devel-${DEP_SDL3_VERSION}-VC.zip)
set(SDL3_PLATFORM  "x64")

if(CMAKE_SIZEOF_VOID_P EQUAL 4)
  set(SDL3_PLATFORM "x86")
endif()

set(SDL3_PATH ${CMAKE_CURRENT_SOURCE_DIR}/deps_${PLATFORM}/SDL3-${DEP_SDL3_VERSION}_${SDL3_PLATFORM})

ExternalProject_Add(SDL3_devel
  URL ${DEP_SDL3_URL_BASE}/${SDL3_DEVEL_PKG}
  URL_HASH SHA1=${DEP_SDL3_SHA1_WINDOWS}
  DOWNLOAD_DIR ${CMAKE_CURRENT_SOURCE_DIR}/deps_${PLATFORM}
  DOWNLOAD_NO_PROGRESS true
  DOWNLOAD_EXTRACT_TIMESTAMP true
  TLS_VERIFY true
  SOURCE_DIR ${SDL3_PATH}/
  BUILD_BYPRODUCTS ${SDL3_PATH}/lib/${SDL3_PLATFORM}/SDL3.lib

  BUILD_COMMAND ${CMAKE_COMMAND} -E echo "Skipping build step."

  INSTALL_COMMAND ${CMAKE_COMMAND} -E copy
    ${SDL3_PATH}/lib/${SDL3_PLATFORM}/SDL3.dll ${CMAKE_CURRENT_SOURCE_DIR}/export

  PATCH_COMMAND ${CMAKE_COMMAND} -E copy
    "${CMAKE_CURRENT_SOURCE_DIR}/cmake/dep_sdl3.cmake" ${SDL3_PATH}/CMakeLists.txt
)

set(SDL3_INCLUDE_DIR ${SDL3_PATH}/include)
set(SDL3_LIBRARY     ${SDL3_PATH}/lib/${SDL3_PLATFORM}/SDL3.lib)

# dirent
dep_dirent()
set(DIRENT_PATH      ${CMAKE_CURRENT_SOURCE_DIR}/deps_${PLATFORM}/dirent-${DEP_DIRENT_VERSION})
set(DIRENT_DEVEL_PKG ${DEP_DIRENT_VERSION}.zip)

ExternalProject_Add(dirent_devel
  URL ${DEP_DIRENT_URL_BASE}/${DIRENT_DEVEL_PKG}
  URL_HASH SHA1=${DEP_DIRENT_SHA1_WINDOWS}
  DOWNLOAD_DIR ${CMAKE_CURRENT_SOURCE_DIR}/deps_${PLATFORM}
  DOWNLOAD_NO_PROGRESS true
  DOWNLOAD_EXTRACT_TIMESTAMP true
  TLS_VERIFY true
  SOURCE_DIR ${DIRENT_PATH}/

  BUILD_COMMAND   ${CMAKE_COMMAND} -E echo "Skipping build step."
  INSTALL_COMMAND ${CMAKE_COMMAND} -E echo "Skipping install step."

  PATCH_COMMAND ${CMAKE_COMMAND} -E copy
    "${CMAKE_CURRENT_SOURCE_DIR}/cmake/dep_dirent.cmake" ${DIRENT_PATH}/CMakeLists.txt
)

set(DIRENT_INCLUDE_DIR ${DIRENT_PATH}/include)

if (CMAKE_C_COMPILER_ID STREQUAL "MSVC")
  set(ADDITIONAL_RUNTIME
    ucrt
    legacy_stdio_definitions
    legacy_stdio_wide_specifiers
  )
endif()

set(PLATFORM_LIBS
  ${CANVENIENT_LIBRARY}
  ${CJSON_LIBRARY}
  ${PCAN_LIBRARY}
  ${POCKETPY_LIBRARY}
  ${SDL3_LIBRARY}
  ${INIH_LIBRARY}
  ${ISOCLINE_LIBRARY}
  ${LUA_LIBRARY}
  ${ADDITIONAL_RUNTIME}
)

set(PLATFORM_CORE_DEPS
  inih_devel
  isocline_devel
  Lua_devel
  CANvenient_devel
  pocketpy_devel
  SDL3_devel
)

include_directories(
  SYSTEM ${SDL3_INCLUDE_DIR}
  SYSTEM ${CANVENIENT_INCLUDE_DIR}
  SYSTEM ${PCAN_INCLUDE_DIR}/../src/pcan/lib
  SYSTEM ${POCKETPY_INCLUDE_DIR}
  SYSTEM ${LUA_INCLUDE_DIR}
  SYSTEM ${INIH_INCLUDE_DIR}
  SYSTEM ${ISOCLINE_INCLUDE_DIR}
  SYSTEM ${CJSON_INCLUDE_DIR}
  SYSTEM ${DIRENT_INCLUDE_DIR}
)

add_compile_definitions(
  _CRT_SECURE_NO_WARNINGS
  WIN32
)
