name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: lukka/get-cmake@latest

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -G "Ninja" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

    - name: List contents of deps_windows directory
      run: dir D:/a/CANopenTerm/CANopenTerm/deps_windows

    - name: List contents of inih-58_build directory
      run: dir D:/a/CANopenTerm/CANopenTerm/deps_windows/inih-58_build

    - name: List contents of lua-5.4.6_windows_build directory
      run: dir D:/a/CANopenTerm/CANopenTerm/deps_windows/lua-5.4.6_windows_build

    - name: Build with CMake
      run: cmake --build build --config Release

    - name: Install WiX Toolset
      run: |
        choco install wix --version=3.11.2

    - name: Build WiX Toolset solution
      run: |
        cd setup
        msbuild /p:Configuration=Release
