name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: lukka/get-cmake@latest

    - name: Configure CMake
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release -G "Ninja" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_FLAGS="-D_DLL -D_MT -Xclang --dependent-lib=msvcrt" -DCMAKE_CXX_FLAGS="-D_DLL -D_MT -Xclang --dependent-lib=msvcrt" -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld -nostdlib++ -lc++ -lc++abi -lunwind"

    - name: Build with CMake
      run: cmake --build build --config Release

    - name: Install WiX Toolset
      run: |
        choco install wix --version=3.11.2

    - name: Build WiX Toolset solution
      run: |
        cd setup
        msbuild /p:Configuration=Release
