name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up CMake
      uses: lukka/get-cmake@latest

    - name: Install dependencies
      run: |
        choco install llvm
        choco install ninja
        choco install vswhere

    - name: Configure CMake
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release -G "Ninja" -T host=x64 -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded

    - name: Build with CMake
      run: cmake --build build --config Release

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: nuget restore setup/setup.sln

    - name: Build WiX Toolset solution
      run: |
        cd setup
        msbuild /p:Configuration=Release /p:Platform=x64

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: setup/CANopenTerm/bin/x64/Release/en-US/CANopenTerm.msi

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: .

    - name: Delete existing release
      uses: dev-drprasad/delete-tag-and-release@v1.1
      with:
        tag_name: latest
        delete_release: true
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          CANopenTerm.msi
        tag_name: latest
        name: "Latest Release"
        body: "This is the latest build of CANopenTerm."
        draft: false
        prerelease: true
        token: ${{ secrets.GITHUB_TOKEN }}
        make_latest: true
