name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: lukka/get-cmake@latest

    - name: Install dependencies
      run: |
        choco install llvm
        choco install ninja

    - name: Configure CMake
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release -G "Ninja" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_FLAGS="-D_DLL -D_MT -Xclang --dependent-lib=msvcrt" -DCMAKE_CXX_FLAGS="-D_DLL -D_MT -Xclang --dependent-lib=msvcrt" -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld-link -nostdlib++ -lmsvcrt -lmsvcprt" -DCMAKE_C_FLAGS_RELEASE="-D_DLL -D_MT -Xclang --dependent-lib=msvcrt" -DCMAKE_CXX_FLAGS_RELEASE="-D_DLL -D_MT -Xclang --dependent-lib=msvcrt" -DCMAKE_SHARED_LINKER_FLAGS_RELEASE="-fuse-ld=lld-link -nostdlib++ -lmsvcrt -lmsvcprt" -DCMAKE_MODULE_LINKER_FLAGS_RELEASE="-fuse-ld=lld-link -nostdlib++ -lmsvcrt -lmsvcprt" -DCMAKE_TRY_COMPILE_TARGET_TYPE=STATIC_LIBRARY

    - name: Build with CMake
      run: cmake --build build --config Release

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: nuget restore setup/setup.sln

    - name: Build WiX Toolset solution
      run: |
        cd setup
        msbuild /p:Configuration=Release /p:Platform=x64
